# Generated by Django 4.2.7 on 2023-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Food', 'Food'), ('Rent', 'Rent'), ('Transport', 'Transport'), ('Relaxing', 'Relaxing')], max_length=100)),
                ('Amount', models.FloatField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
